import { useEffect, useState } from 'react';
import { BarChart3, Boxes, Image, LayoutDashboard, Plus, RefreshCw, Search, ShoppingBag, Tags, Users } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import toast from 'react-hot-toast';
import { adminAPI, productAPI } from '../api';

const sections = [['overview', 'Overview', LayoutDashboard], ['products', 'Products', Boxes], ['orders', 'Orders', ShoppingBag], ['categories', 'Categories', Tags], ['customers', 'Customers', Users], ['homepage', 'Homepage', Image]];
const statuses = ['placed', 'confirmed', 'packed', 'shipped', 'out_for_delivery', 'delivered', 'cancelled'];
const money = (value = 0) => `\u20b9${Number(value).toLocaleString('en-IN')}`;

function ProductForm({ product, categories, sellers, onSaved }) {
  const [form, setForm] = useState(() => product ? {
    name: product.name || '', description: product.description || '', brand: product.brand || '',
    category: product.category?._id || product.category || '', seller: product.seller?._id || product.seller || '',
    imageUrl: product.images?.[0]?.url || '', price: product.variants?.[0]?.price || '',
    mrp: product.variants?.[0]?.mrp || '', stock: product.variants?.[0]?.stock || '', sku: product.variants?.[0]?.sku || '',
    isFeatured: Boolean(product.isFeatured), isNewArrival: Boolean(product.isNewArrival), isBestSeller: Boolean(product.isBestSeller),
  } : { name: '', description: '', brand: '', category: '', seller: '', imageUrl: '', price: '', mrp: '', stock: '', sku: '', isFeatured: false, isNewArrival: false, isBestSeller: false });
  const [saving, setSaving] = useState(false);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => {
    event.preventDefault();
    if (!form.name || !form.category || !form.seller || !form.price || !form.mrp || !form.stock) return toast.error('Complete the required fields');
    setSaving(true);
    try {
      const payload = { ...form, variants: [{ sku: form.sku || 'SKU-001', price: Number(form.price), mrp: Number(form.mrp), stock: Number(form.stock) }] };
      if (product?._id) await productAPI.updateProduct(product._id, payload);
      else await productAPI.createProduct(payload);
      toast.success(product ? 'Product updated' : 'Product created'); onSaved();
    } catch (error) { toast.error(error.response?.data?.message || 'Could not create product'); }
    finally { setSaving(false); }
  };
  return <form onSubmit={submit} className="card p-5 grid sm:grid-cols-2 gap-4 mb-6">
    <h2 className="font-heading text-xl font-bold sm:col-span-2">{product ? 'Edit product' : 'Add product'}</h2>
    {['name', 'brand', 'price', 'mrp', 'stock', 'sku'].map((key) => <label className="label" key={key}>{key === 'name' ? 'Product name *' : key.toUpperCase()}<input className="input mt-1" type={['price', 'mrp', 'stock'].includes(key) ? 'number' : 'text'} value={form[key]} onChange={(event) => set(key, event.target.value)} /></label>)}
    <label className="label">Category *<select className="input mt-1" value={form.category} onChange={(event) => set('category', event.target.value)}><option value="">Select category</option>{categories.filter((item) => !item.parentCategory).map((item) => <option value={item._id} key={item._id}>{item.name}</option>)}</select></label>
    <label className="label">Seller *<select className="input mt-1" value={form.seller} onChange={(event) => set('seller', event.target.value)}><option value="">Select seller</option>{sellers.map((item) => <option value={item.sellerProfile || item._id} key={item._id}>{item.name} ({item.email})</option>)}</select></label>
    <label className="label sm:col-span-2">Image URL<input className="input mt-1" value={form.imageUrl} onChange={(event) => set('imageUrl', event.target.value)} placeholder="https://..." /></label>
    <label className="label sm:col-span-2">Description<textarea className="input mt-1 min-h-20" value={form.description} onChange={(event) => set('description', event.target.value)} /></label>
    <div className="sm:col-span-2 flex flex-wrap gap-4">{[['isFeatured', 'Featured'], ['isNewArrival', 'New arrival'], ['isBestSeller', 'Best seller']].map(([key, label]) => <label className="flex items-center gap-2 text-sm" key={key}><input type="checkbox" checked={form[key]} onChange={(event) => set(key, event.target.checked)} />{label}</label>)}</div>
    <button className="btn-primary sm:col-span-2" disabled={saving}>{saving ? 'Saving...' : 'Create product'}</button>
  </form>;
}

function Orders({ orders, reload }) {
  const update = async (id, status) => { try { await adminAPI.updateOrderStatus(id, { status }); toast.success('Order status updated'); reload(); } catch (error) { toast.error(error.response?.data?.message || 'Update failed'); } };
  return <div className="card overflow-hidden"><div className="p-5"><h2 className="font-heading text-xl font-bold">Orders</h2><p className="text-sm text-gray-400">Manage payment and fulfillment status.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Order</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Payment</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Update</th></tr></thead><tbody className="divide-y">{orders.map((order) => <tr key={order._id}><td className="px-5 py-4 font-medium">{order.orderNumber || order._id.slice(-8)}</td><td className="px-5 py-4">{order.user?.name || 'Unknown'}<small className="block text-gray-400">{order.user?.email}</small></td><td className="px-5 py-4 font-semibold">{money(order.totalAmount)}</td><td className="px-5 py-4 capitalize">{order.paymentMethod}<small className="block text-gray-400">{order.paymentStatus}</small></td><td className="px-5 py-4"><span className="badge-primary capitalize">{order.orderStatus.replaceAll('_', ' ')}</span></td><td className="px-5 py-4"><select className="input py-1 text-xs" value="" onChange={(event) => update(order._id, event.target.value)}><option value="">Update</option>{statuses.filter((item) => !['placed', 'cancelled'].includes(item)).map((item) => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select></td></tr>)}</tbody></table>{orders.length === 0 && <p className="p-8 text-center text-gray-400">No orders found.</p>}</div></div>;
}

export default function AdminDashboardPage() {
  const [section, setSection] = useState('overview');
  const [data, setData] = useState({ dashboard: null, products: [], categories: [], orders: [], users: [], sellers: [], banners: [] });
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [editingProduct, setEditingProduct] = useState(null);
  const load = async () => { setLoading(true); try { const [dashboard, products, categories, orders, users, banners, sellers] = await Promise.all([adminAPI.getDashboard(), adminAPI.getProducts({ limit: 100 }), adminAPI.getCategories(), adminAPI.getAllOrders({ limit: 100 }), adminAPI.getAllUsers({ role: 'customer', limit: 100 }), adminAPI.getBanners(), adminAPI.getAllUsers({ role: 'seller', limit: 100 })]); setData({ dashboard: dashboard.data.data, products: products.data.data.products, categories: categories.data.data.categories, orders: orders.data.data.orders, users: users.data.data.users, banners: banners.data.data.banners, sellers: sellers.data.data.users }); } catch (error) { toast.error(error.response?.data?.message || 'Could not load admin data'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const toggleProduct = async (product) => { try { await productAPI.updateProduct(product._id, { isActive: !product.isActive }); toast.success('Product visibility updated'); load(); } catch (error) { toast.error(error.response?.data?.message || 'Could not update product'); } };
  const toggleUser = async (user) => { try { await adminAPI.toggleUserStatus(user._id); toast.success('Customer status updated'); load(); } catch (error) { toast.error(error.response?.data?.message || 'Could not update customer'); } };
  if (loading && !data.dashboard) return <div className="min-h-screen flex items-center justify-center text-gray-500">Loading admin workspace...</div>;
  const { dashboard } = data;
  const counts = Object.fromEntries((dashboard.ordersByStatus || []).map((item) => [item._id, item.count]));
  const products = data.products.filter((item) => `${item.name} ${item.brand || ''}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="min-h-[calc(100vh-80px)] bg-gray-50 dark:bg-dark-900"><div className="max-w-[1500px] mx-auto px-4 sm:px-6 lg:px-8 py-6"><div className="flex justify-between gap-4 mb-6"><div><p className="text-xs uppercase tracking-[0.2em] text-primary-500 font-semibold">Trove commerce control</p><h1 className="font-heading text-3xl font-bold">Admin workspace</h1></div><button className="btn-ghost" onClick={load} disabled={loading}><RefreshCw size={16} /> Sync data</button></div><nav className="flex gap-1 overflow-x-auto border-b mb-6">{sections.map(([key, label, Icon]) => <button key={key} onClick={() => setSection(key)} className={`flex items-center gap-2 whitespace-nowrap px-4 py-3 text-sm border-b-2 ${section === key ? 'border-primary-500 text-primary-600' : 'border-transparent text-gray-500'}`}><Icon size={16} />{label}</button>)}</nav>
    {section === 'overview' && <div className="space-y-6"><div className="grid grid-cols-2 xl:grid-cols-4 gap-4">{[['Revenue', money(dashboard.stats.totalRevenue)], ['Orders', dashboard.stats.totalOrders], ['Customers', dashboard.stats.totalUsers], ['Products', dashboard.stats.totalProducts]].map(([label, value]) => <div className="card p-5" key={label}><p className="text-sm text-gray-500">{label}</p><p className="font-heading text-2xl font-bold mt-1">{value}</p></div>)}</div><div className="grid grid-cols-2 sm:grid-cols-4 xl:grid-cols-7 gap-3">{statuses.map((status) => <div className="card p-3" key={status}><p className="text-[11px] text-gray-400 uppercase">{status.replaceAll('_', ' ')}</p><p className="text-xl font-bold">{counts[status] || 0}</p></div>)}</div><div className="grid xl:grid-cols-3 gap-6"><section className="card p-5 xl:col-span-2"><h2 className="font-heading font-bold mb-4">Revenue, last 30 days</h2><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={dashboard.revenueByDay}><CartesianGrid vertical={false} stroke="#e5e7eb" /><XAxis dataKey="_id" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip formatter={(value) => [money(value), 'Revenue']} /><Bar dataKey="revenue" fill="#4E4FEB" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="card p-5"><h2 className="font-heading font-bold mb-4">Top products</h2>{dashboard.topProducts.map((item) => <div className="flex gap-3 py-2" key={item._id}><span className="text-sm truncate flex-1">{item.name}</span><span className="text-xs text-gray-400">{item.soldCount || 0} sold</span></div>)}</section></div><Orders orders={dashboard.recentOrders} reload={load} /></div>}
    {section === 'products' && <div><ProductForm product={editingProduct} categories={data.categories} sellers={data.sellers} onSaved={() => { setEditingProduct(null); load(); }} /><div className="card overflow-hidden"><div className="p-5 flex justify-between gap-3"><div><h2 className="font-heading text-xl font-bold">Catalog</h2><p className="text-sm text-gray-400">Manage products and homepage placement.</p></div><label className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" /><input className="input pl-9" placeholder="Search catalog" value={search} onChange={(event) => setSearch(event.target.value)} /></label></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Product</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Price / stock</th><th className="px-5 py-3">Placement</th><th className="px-5 py-3">Visibility</th><th className="px-5 py-3">Action</th></tr></thead><tbody className="divide-y">{products.map((item) => <tr key={item._id}><td className="px-5 py-4 flex gap-3 items-center"><img className="w-12 h-12 rounded object-cover" src={item.images?.[0]?.url} alt="" /><span><b>{item.name}</b><small className="block text-gray-400">{item.brand}</small></span></td><td className="px-5 py-4">{item.category?.name}</td><td className="px-5 py-4">{money(item.variants?.[0]?.price)}<small className="block text-gray-400">{item.variants?.[0]?.stock || 0} stock</small></td><td className="px-5 py-4">{item.isFeatured && <span className="badge-amber mr-1">Featured</span>}{item.isNewArrival && <span className="badge-primary">New</span>}</td><td className="px-5 py-4"><span className={item.isActive ? 'badge-success' : 'badge-error'}>{item.isActive ? 'Published' : 'Hidden'}</span></td><td className="px-5 py-4"><button className="text-primary-600 mr-3" onClick={() => setEditingProduct(item)}>Edit</button><button className="text-gray-500" onClick={() => toggleProduct(item)}>{item.isActive ? 'Hide' : 'Publish'}</button></td></tr>)}</tbody></table></div></div></div>}
    {section === 'orders' && <Orders orders={data.orders} reload={load} />}
    {section === 'categories' && <div className="grid lg:grid-cols-3 gap-6"><section className="card p-5 lg:col-span-2"><h2 className="font-heading text-xl font-bold mb-4">Categories</h2><div className="grid sm:grid-cols-2 gap-3">{data.categories.map((item) => <div className="border rounded-xl p-4 flex justify-between" key={item._id}><b>{item.name}</b><span className="badge-primary">{item.isActive ? 'Live' : 'Hidden'}</span></div>)}</div></section><CategoryForm reload={load} /></div>}
    {section === 'customers' && <div className="card overflow-hidden"><div className="p-5"><h2 className="font-heading text-xl font-bold">Customers</h2></div><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Joined</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Action</th></tr></thead><tbody className="divide-y">{data.users.map((user) => <tr key={user._id}><td className="px-5 py-4"><b>{user.name}</b><small className="block text-gray-400">{user.email}</small></td><td className="px-5 py-4">{new Date(user.createdAt).toLocaleDateString()}</td><td className="px-5 py-4">{user.isActive ? 'Active' : 'Blocked'}</td><td className="px-5 py-4"><button className="text-primary-600" onClick={() => toggleUser(user)}>{user.isActive ? 'Block' : 'Activate'}</button></td></tr>)}</tbody></table></div>}
    {section === 'homepage' && <div className="card p-5"><h2 className="font-heading text-xl font-bold mb-4">Homepage content</h2><div className="grid sm:grid-cols-2 gap-4">{data.banners.map((banner) => <div className="border rounded-xl p-3" key={banner._id}><img src={banner.image?.url} className="w-full h-32 object-cover rounded-lg" alt="" /><b className="block mt-2">{banner.title}</b><small className="text-gray-400">{banner.position} Â· {banner.isActive ? 'Active' : 'Inactive'}</small></div>)}</div><p className="text-sm text-gray-400 mt-5">Use the product placement flags in Products to control Featured, New arrival, and Best seller sections.</p></div>}
  </div></div>;
}

function CategoryForm({ reload }) { const [name, setName] = useState(''); const submit = async (event) => { event.preventDefault(); if (!name.trim()) return; try { await adminAPI.createCategory({ name, slug: name.toLowerCase().trim().replace(/\s+/g, '-') }); toast.success('Category created'); setName(''); reload(); } catch (error) { toast.error(error.response?.data?.message || 'Could not create category'); } }; return <section className="card p-5"><h2 className="font-heading font-bold mb-4">Add category</h2><form onSubmit={submit} className="space-y-3"><input className="input" placeholder="Category name" value={name} onChange={(event) => setName(event.target.value)} /><button className="btn-primary w-full"><Plus size={16} /> Add category</button></form></section>; }
